require("dotenv").config({ quiet: true });

const mongoose = require("mongoose");
const { connectDatabase, Expert } = require("../models/app-models.cjs");

const expertProfiles = [
  { name: "Aarav Mehta", email: "aarav.mehta@experts.solvenut.demo", field: "programming", experience: 11, price: 1299, headline: "Staff engineer for scalable web products and practical architecture decisions.", skills: ["React", "Node.js", "System design"], languages: ["English", "Hindi"], availability: "Available today", sessionCount: 184 },
  { name: "Priya Nair", email: "priya.nair@experts.solvenut.demo", field: "programming", experience: 8, price: 999, headline: "Full-stack mentor helping developers debug, ship, and level up confidently.", skills: ["JavaScript", "Python", "Code reviews"], languages: ["English", "Malayalam"], availability: "Replies within 2 hours", sessionCount: 142 },
  { name: "Kabir Shah", email: "kabir.shah@experts.solvenut.demo", field: "programming", experience: 9, price: 1099, headline: "Backend specialist for APIs, databases, and reliable product foundations.", skills: ["APIs", "PostgreSQL", "Performance"], languages: ["English", "Gujarati"], availability: "Available this week", sessionCount: 119 },
  { name: "Neha Kapoor", email: "neha.kapoor@experts.solvenut.demo", field: "devops", experience: 10, price: 1399, headline: "Cloud and DevOps advisor for dependable releases without overengineering.", skills: ["AWS", "Docker", "CI/CD"], languages: ["English", "Hindi"], availability: "Available today", sessionCount: 176 },
  { name: "Rohan Iyer", email: "rohan.iyer@experts.solvenut.demo", field: "devops", experience: 7, price: 1099, headline: "SRE coach for observability, incident response, and production readiness.", skills: ["Kubernetes", "Terraform", "Monitoring"], languages: ["English", "Tamil"], availability: "Replies within 4 hours", sessionCount: 97 },
  { name: "Isha Verma", email: "isha.verma@experts.solvenut.demo", field: "academics", experience: 12, price: 899, headline: "Research and study strategist for high-stakes exams and graduate applications.", skills: ["Study plans", "Research", "Applications"], languages: ["English", "Hindi"], availability: "Available this week", sessionCount: 216 },
  { name: "Arjun Sen", email: "arjun.sen@experts.solvenut.demo", field: "academics", experience: 6, price: 699, headline: "Learning systems mentor for focused preparation and better academic habits.", skills: ["Exam prep", "Learning systems", "Time management"], languages: ["English", "Bengali"], availability: "Available tomorrow", sessionCount: 88 },
  { name: "Meera Joshi", email: "meera.joshi@experts.solvenut.demo", field: "career", experience: 13, price: 1199, headline: "Career strategist for transitions, interviews, and senior-level positioning.", skills: ["Interviews", "Career change", "Compensation"], languages: ["English", "Hindi"], availability: "Available today", sessionCount: 241 },
  { name: "Vikram Rao", email: "vikram.rao@experts.solvenut.demo", field: "career", experience: 9, price: 999, headline: "Leadership coach for managers building clarity, influence, and momentum.", skills: ["Leadership", "Communication", "Job search"], languages: ["English", "Telugu"], availability: "Replies within 2 hours", sessionCount: 163 },
  { name: "Sana Qureshi", email: "sana.qureshi@experts.solvenut.demo", field: "business", experience: 14, price: 1499, headline: "Startup operator for validation, pricing, and practical growth strategy.", skills: ["Go-to-market", "Pricing", "Operations"], languages: ["English", "Urdu"], availability: "Available this week", sessionCount: 205 },
  { name: "Dev Malhotra", email: "dev.malhotra@experts.solvenut.demo", field: "business", experience: 8, price: 1199, headline: "Product and business advisor for early teams making smarter bets.", skills: ["Product strategy", "Market research", "Roadmaps"], languages: ["English", "Hindi"], availability: "Available tomorrow", sessionCount: 132 },
  { name: "Dr. Ananya Bose", email: "ananya.bose@experts.solvenut.demo", field: "medical", experience: 11, price: 1499, headline: "Health education and care-navigation guidance for informed next steps.", skills: ["Care navigation", "Wellness", "Health education"], languages: ["English", "Bengali"], availability: "Available this week", sessionCount: 154 },
  { name: "Sofia Ramirez", email: "sofia.ramirez@experts.solvenut.demo", field: "programming", experience: 12, price: 1399, headline: "Frontend architect helping product teams turn complex interfaces into fast, accessible experiences.", summary: "Sofia has led design-system and frontend platform work for global SaaS products. Bring a UI architecture question, a performance bottleneck, or a team decision.", skills: ["TypeScript", "Design systems", "Web performance"], languages: ["English", "Spanish"], location: "Madrid, Spain", availability: "Available today", sessionCount: 198, avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=640&q=80" },
  { name: "Marcus Okafor", email: "marcus.okafor@experts.solvenut.demo", field: "programming", experience: 15, price: 1599, headline: "Platform engineer for API reliability, security reviews, and systems that scale with the business.", summary: "Marcus works with engineering leads on architecture trade-offs, API design, and practical security improvements that teams can ship.", skills: ["System design", "API security", "Go"], languages: ["English", "French"], location: "London, UK", availability: "Replies within 2 hours", sessionCount: 276, avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=640&q=80" },
  { name: "Linh Tran", email: "linh.tran@experts.solvenut.demo", field: "devops", experience: 10, price: 1299, headline: "Cloud reliability mentor for calmer releases, useful observability, and resilient teams.", summary: "Linh helps growing teams move from firefighting to repeatable operations through sensible cloud architecture and incident learning.", skills: ["AWS", "Kubernetes", "SRE"], languages: ["English", "Vietnamese"], location: "Singapore", availability: "Available this week", sessionCount: 167, avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=640&q=80" },
  { name: "Fatima Zahra", email: "fatima.zahra@experts.solvenut.demo", field: "devops", experience: 8, price: 1099, headline: "DevOps coach for release automation, cloud cost clarity, and production readiness.", summary: "Fatima turns deployment friction into a clear improvement plan for teams that are shipping quickly and learning as they grow.", skills: ["CI/CD", "Azure", "Cloud cost"], languages: ["English", "Arabic", "French"], location: "Casablanca, Morocco", availability: "Available tomorrow", sessionCount: 121, avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=640&q=80" },
  { name: "Elena Petrov", email: "elena.petrov@experts.solvenut.demo", field: "academics", experience: 14, price: 999, headline: "Research mentor for clear questions, stronger applications, and focused academic planning.", summary: "Elena supports students and early researchers with study systems, research framing, and realistic graduate-school decisions.", skills: ["Research design", "Academic writing", "Applications"], languages: ["English", "Russian"], location: "Berlin, Germany", availability: "Available this week", sessionCount: 232, avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=640&q=80" },
  { name: "Noah Williams", email: "noah.williams@experts.solvenut.demo", field: "academics", experience: 9, price: 799, headline: "Learning strategist for exam preparation, deep work, and sustainable study routines.", summary: "Noah helps learners build a practical plan around their schedule, energy, and assessment goals instead of relying on vague motivation.", skills: ["Exam prep", "Study systems", "Time management"], languages: ["English"], location: "Toronto, Canada", availability: "Replies within 4 hours", sessionCount: 143, avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=640&q=80" },
  { name: "Kavya Menon", email: "kavya.menon@experts.solvenut.demo", field: "career", experience: 12, price: 1199, headline: "Career transition advisor for stronger positioning, thoughtful offers, and confident interviews.", summary: "Kavya has coached professionals through role changes and promotions with a focus on evidence, trade-offs, and an achievable next move.", skills: ["Career change", "Interview strategy", "Negotiation"], languages: ["English", "Hindi", "Malayalam"], location: "Bengaluru, India", availability: "Available today", sessionCount: 264, avatar: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=640&q=80" },
  { name: "Daniel Brooks", email: "daniel.brooks@experts.solvenut.demo", field: "career", experience: 16, price: 1499, headline: "Leadership advisor for managers making difficult people and priority decisions.", summary: "Daniel works with new and experienced leaders on communication, team clarity, and the decisions that shape a healthy operating rhythm.", skills: ["Leadership", "Executive communication", "Team design"], languages: ["English"], location: "New York, USA", availability: "Available this week", sessionCount: 318, avatar: "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=640&q=80" },
  { name: "Amina Yusuf", email: "amina.yusuf@experts.solvenut.demo", field: "business", experience: 13, price: 1399, headline: "Startup operator for customer discovery, pricing decisions, and focused go-to-market plans.", summary: "Amina helps founders turn a broad idea into a small set of testable assumptions and a practical sequence of experiments.", skills: ["Customer discovery", "Pricing", "Go-to-market"], languages: ["English", "Swahili", "Arabic"], location: "Nairobi, Kenya", availability: "Available today", sessionCount: 187, avatar: "https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&w=640&q=80" },
  { name: "Lucas Ferreira", email: "lucas.ferreira@experts.solvenut.demo", field: "business", experience: 11, price: 1299, headline: "Product strategy partner for early teams choosing what to validate, build, and measure.", summary: "Lucas helps product teams connect customer signals to a clear roadmap, sensible metrics, and decisions they can revisit with evidence.", skills: ["Product strategy", "Roadmaps", "Market research"], languages: ["English", "Portuguese"], location: "São Paulo, Brazil", availability: "Available tomorrow", sessionCount: 156, avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=640&q=80" },
];

async function seedExperts() {
  await connectDatabase(process.env.MONGO_URI || "mongodb://localhost:27017/solutionhub");

  await Expert.bulkWrite(
    expertProfiles.map((profile) => ({
      updateOne: {
        filter: { email: profile.email },
        update: { $set: { ...profile, role: "expert", status: "approved" } },
        upsert: true,
      },
    }))
  );

  console.log(`Seeded ${expertProfiles.length} approved expert profiles.`);
}

if (require.main === module) {
  seedExperts()
    .catch((error) => {
      console.error("Unable to seed experts:", error.message);
      process.exitCode = 1;
    })
    .finally(() => mongoose.disconnect());
}

module.exports = { expertProfiles, seedExperts };
